// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service_error.proto

#ifndef PROTOBUF_service_5ferror_2eproto__INCLUDED
#define PROTOBUF_service_5ferror_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "servic_result.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_service_5ferror_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsServiceErrorImpl();
void InitDefaultsServiceError();
inline void InitDefaults() {
  InitDefaultsServiceError();
}
}  // namespace protobuf_service_5ferror_2eproto
namespace crucis {
class ServiceError;
class ServiceErrorDefaultTypeInternal;
extern ServiceErrorDefaultTypeInternal _ServiceError_default_instance_;
}  // namespace crucis
namespace crucis {

// ===================================================================

class ServiceError : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:crucis.ServiceError) */ {
 public:
  ServiceError();
  virtual ~ServiceError();

  ServiceError(const ServiceError& from);

  inline ServiceError& operator=(const ServiceError& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ServiceError(ServiceError&& from) noexcept
    : ServiceError() {
    *this = ::std::move(from);
  }

  inline ServiceError& operator=(ServiceError&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ServiceError& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ServiceError* internal_default_instance() {
    return reinterpret_cast<const ServiceError*>(
               &_ServiceError_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(ServiceError* other);
  friend void swap(ServiceError& a, ServiceError& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ServiceError* New() const PROTOBUF_FINAL { return New(NULL); }

  ServiceError* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ServiceError& from);
  void MergeFrom(const ServiceError& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ServiceError* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .crucis.ServicResult error = 1;
  void clear_error();
  static const int kErrorFieldNumber = 1;
  ::crucis::ServicResult error() const;
  void set_error(::crucis::ServicResult value);

  // @@protoc_insertion_point(class_scope:crucis.ServiceError)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  int error_;
  mutable int _cached_size_;
  friend struct ::protobuf_service_5ferror_2eproto::TableStruct;
  friend void ::protobuf_service_5ferror_2eproto::InitDefaultsServiceErrorImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ServiceError

// .crucis.ServicResult error = 1;
inline void ServiceError::clear_error() {
  error_ = 0;
}
inline ::crucis::ServicResult ServiceError::error() const {
  // @@protoc_insertion_point(field_get:crucis.ServiceError.error)
  return static_cast< ::crucis::ServicResult >(error_);
}
inline void ServiceError::set_error(::crucis::ServicResult value) {
  
  error_ = value;
  // @@protoc_insertion_point(field_set:crucis.ServiceError.error)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace crucis

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_service_5ferror_2eproto__INCLUDED
