// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service_factory_param_define.proto

#ifndef PROTOBUF_service_5ffactory_5fparam_5fdefine_2eproto__INCLUDED
#define PROTOBUF_service_5ffactory_5fparam_5fdefine_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "auth_error_code.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_service_5ffactory_5fparam_5fdefine_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[9];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsNewServiceSingletonRequestImpl();
void InitDefaultsNewServiceSingletonRequest();
void InitDefaultsNewServiceRequestImpl();
void InitDefaultsNewServiceRequest();
void InitDefaultsSyncServicesRequestImpl();
void InitDefaultsSyncServicesRequest();
void InitDefaultsBindServiceRequestImpl();
void InitDefaultsBindServiceRequest();
void InitDefaultsAuthResultRequestImpl();
void InitDefaultsAuthResultRequest();
void InitDefaultsDeleteServiceRequestImpl();
void InitDefaultsDeleteServiceRequest();
void InitDefaultsReloadServiceRequestImpl();
void InitDefaultsReloadServiceRequest();
void InitDefaultsSyncServicesResponseImpl();
void InitDefaultsSyncServicesResponse();
void InitDefaultsBindServiceResponseImpl();
void InitDefaultsBindServiceResponse();
inline void InitDefaults() {
  InitDefaultsNewServiceSingletonRequest();
  InitDefaultsNewServiceRequest();
  InitDefaultsSyncServicesRequest();
  InitDefaultsBindServiceRequest();
  InitDefaultsAuthResultRequest();
  InitDefaultsDeleteServiceRequest();
  InitDefaultsReloadServiceRequest();
  InitDefaultsSyncServicesResponse();
  InitDefaultsBindServiceResponse();
}
}  // namespace protobuf_service_5ffactory_5fparam_5fdefine_2eproto
namespace crucis {
class AuthResultRequest;
class AuthResultRequestDefaultTypeInternal;
extern AuthResultRequestDefaultTypeInternal _AuthResultRequest_default_instance_;
class BindServiceRequest;
class BindServiceRequestDefaultTypeInternal;
extern BindServiceRequestDefaultTypeInternal _BindServiceRequest_default_instance_;
class BindServiceResponse;
class BindServiceResponseDefaultTypeInternal;
extern BindServiceResponseDefaultTypeInternal _BindServiceResponse_default_instance_;
class DeleteServiceRequest;
class DeleteServiceRequestDefaultTypeInternal;
extern DeleteServiceRequestDefaultTypeInternal _DeleteServiceRequest_default_instance_;
class NewServiceRequest;
class NewServiceRequestDefaultTypeInternal;
extern NewServiceRequestDefaultTypeInternal _NewServiceRequest_default_instance_;
class NewServiceSingletonRequest;
class NewServiceSingletonRequestDefaultTypeInternal;
extern NewServiceSingletonRequestDefaultTypeInternal _NewServiceSingletonRequest_default_instance_;
class ReloadServiceRequest;
class ReloadServiceRequestDefaultTypeInternal;
extern ReloadServiceRequestDefaultTypeInternal _ReloadServiceRequest_default_instance_;
class SyncServicesRequest;
class SyncServicesRequestDefaultTypeInternal;
extern SyncServicesRequestDefaultTypeInternal _SyncServicesRequest_default_instance_;
class SyncServicesResponse;
class SyncServicesResponseDefaultTypeInternal;
extern SyncServicesResponseDefaultTypeInternal _SyncServicesResponse_default_instance_;
}  // namespace crucis
namespace crucis {

// ===================================================================

class NewServiceSingletonRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:crucis.NewServiceSingletonRequest) */ {
 public:
  NewServiceSingletonRequest();
  virtual ~NewServiceSingletonRequest();

  NewServiceSingletonRequest(const NewServiceSingletonRequest& from);

  inline NewServiceSingletonRequest& operator=(const NewServiceSingletonRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  NewServiceSingletonRequest(NewServiceSingletonRequest&& from) noexcept
    : NewServiceSingletonRequest() {
    *this = ::std::move(from);
  }

  inline NewServiceSingletonRequest& operator=(NewServiceSingletonRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const NewServiceSingletonRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NewServiceSingletonRequest* internal_default_instance() {
    return reinterpret_cast<const NewServiceSingletonRequest*>(
               &_NewServiceSingletonRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(NewServiceSingletonRequest* other);
  friend void swap(NewServiceSingletonRequest& a, NewServiceSingletonRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline NewServiceSingletonRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  NewServiceSingletonRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NewServiceSingletonRequest& from);
  void MergeFrom(const NewServiceSingletonRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NewServiceSingletonRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 service_type = 1;
  void clear_service_type();
  static const int kServiceTypeFieldNumber = 1;
  ::google::protobuf::uint32 service_type() const;
  void set_service_type(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:crucis.NewServiceSingletonRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 service_type_;
  mutable int _cached_size_;
  friend struct ::protobuf_service_5ffactory_5fparam_5fdefine_2eproto::TableStruct;
  friend void ::protobuf_service_5ffactory_5fparam_5fdefine_2eproto::InitDefaultsNewServiceSingletonRequestImpl();
};
// -------------------------------------------------------------------

class NewServiceRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:crucis.NewServiceRequest) */ {
 public:
  NewServiceRequest();
  virtual ~NewServiceRequest();

  NewServiceRequest(const NewServiceRequest& from);

  inline NewServiceRequest& operator=(const NewServiceRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  NewServiceRequest(NewServiceRequest&& from) noexcept
    : NewServiceRequest() {
    *this = ::std::move(from);
  }

  inline NewServiceRequest& operator=(NewServiceRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const NewServiceRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NewServiceRequest* internal_default_instance() {
    return reinterpret_cast<const NewServiceRequest*>(
               &_NewServiceRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(NewServiceRequest* other);
  friend void swap(NewServiceRequest& a, NewServiceRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline NewServiceRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  NewServiceRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NewServiceRequest& from);
  void MergeFrom(const NewServiceRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NewServiceRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 object_id = 2;
  void clear_object_id();
  static const int kObjectIdFieldNumber = 2;
  ::google::protobuf::uint64 object_id() const;
  void set_object_id(::google::protobuf::uint64 value);

  // uint32 service_type = 1;
  void clear_service_type();
  static const int kServiceTypeFieldNumber = 1;
  ::google::protobuf::uint32 service_type() const;
  void set_service_type(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:crucis.NewServiceRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 object_id_;
  ::google::protobuf::uint32 service_type_;
  mutable int _cached_size_;
  friend struct ::protobuf_service_5ffactory_5fparam_5fdefine_2eproto::TableStruct;
  friend void ::protobuf_service_5ffactory_5fparam_5fdefine_2eproto::InitDefaultsNewServiceRequestImpl();
};
// -------------------------------------------------------------------

class SyncServicesRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:crucis.SyncServicesRequest) */ {
 public:
  SyncServicesRequest();
  virtual ~SyncServicesRequest();

  SyncServicesRequest(const SyncServicesRequest& from);

  inline SyncServicesRequest& operator=(const SyncServicesRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SyncServicesRequest(SyncServicesRequest&& from) noexcept
    : SyncServicesRequest() {
    *this = ::std::move(from);
  }

  inline SyncServicesRequest& operator=(SyncServicesRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SyncServicesRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SyncServicesRequest* internal_default_instance() {
    return reinterpret_cast<const SyncServicesRequest*>(
               &_SyncServicesRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(SyncServicesRequest* other);
  friend void swap(SyncServicesRequest& a, SyncServicesRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SyncServicesRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  SyncServicesRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SyncServicesRequest& from);
  void MergeFrom(const SyncServicesRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SyncServicesRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 service_types = 1;
  int service_types_size() const;
  void clear_service_types();
  static const int kServiceTypesFieldNumber = 1;
  ::google::protobuf::uint32 service_types(int index) const;
  void set_service_types(int index, ::google::protobuf::uint32 value);
  void add_service_types(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      service_types() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_service_types();

  // repeated uint32 service_ids = 2;
  int service_ids_size() const;
  void clear_service_ids();
  static const int kServiceIdsFieldNumber = 2;
  ::google::protobuf::uint32 service_ids(int index) const;
  void set_service_ids(int index, ::google::protobuf::uint32 value);
  void add_service_ids(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      service_ids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_service_ids();

  // @@protoc_insertion_point(class_scope:crucis.SyncServicesRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > service_types_;
  mutable int _service_types_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > service_ids_;
  mutable int _service_ids_cached_byte_size_;
  mutable int _cached_size_;
  friend struct ::protobuf_service_5ffactory_5fparam_5fdefine_2eproto::TableStruct;
  friend void ::protobuf_service_5ffactory_5fparam_5fdefine_2eproto::InitDefaultsSyncServicesRequestImpl();
};
// -------------------------------------------------------------------

class BindServiceRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:crucis.BindServiceRequest) */ {
 public:
  BindServiceRequest();
  virtual ~BindServiceRequest();

  BindServiceRequest(const BindServiceRequest& from);

  inline BindServiceRequest& operator=(const BindServiceRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BindServiceRequest(BindServiceRequest&& from) noexcept
    : BindServiceRequest() {
    *this = ::std::move(from);
  }

  inline BindServiceRequest& operator=(BindServiceRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BindServiceRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BindServiceRequest* internal_default_instance() {
    return reinterpret_cast<const BindServiceRequest*>(
               &_BindServiceRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(BindServiceRequest* other);
  friend void swap(BindServiceRequest& a, BindServiceRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BindServiceRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  BindServiceRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const BindServiceRequest& from);
  void MergeFrom(const BindServiceRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(BindServiceRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 service_type = 1;
  void clear_service_type();
  static const int kServiceTypeFieldNumber = 1;
  ::google::protobuf::int32 service_type() const;
  void set_service_type(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:crucis.BindServiceRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 service_type_;
  mutable int _cached_size_;
  friend struct ::protobuf_service_5ffactory_5fparam_5fdefine_2eproto::TableStruct;
  friend void ::protobuf_service_5ffactory_5fparam_5fdefine_2eproto::InitDefaultsBindServiceRequestImpl();
};
// -------------------------------------------------------------------

class AuthResultRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:crucis.AuthResultRequest) */ {
 public:
  AuthResultRequest();
  virtual ~AuthResultRequest();

  AuthResultRequest(const AuthResultRequest& from);

  inline AuthResultRequest& operator=(const AuthResultRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AuthResultRequest(AuthResultRequest&& from) noexcept
    : AuthResultRequest() {
    *this = ::std::move(from);
  }

  inline AuthResultRequest& operator=(AuthResultRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const AuthResultRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AuthResultRequest* internal_default_instance() {
    return reinterpret_cast<const AuthResultRequest*>(
               &_AuthResultRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(AuthResultRequest* other);
  friend void swap(AuthResultRequest& a, AuthResultRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AuthResultRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  AuthResultRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AuthResultRequest& from);
  void MergeFrom(const AuthResultRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AuthResultRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .crucis.AuthErrorCode result = 1;
  void clear_result();
  static const int kResultFieldNumber = 1;
  ::crucis::AuthErrorCode result() const;
  void set_result(::crucis::AuthErrorCode value);

  // @@protoc_insertion_point(class_scope:crucis.AuthResultRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  int result_;
  mutable int _cached_size_;
  friend struct ::protobuf_service_5ffactory_5fparam_5fdefine_2eproto::TableStruct;
  friend void ::protobuf_service_5ffactory_5fparam_5fdefine_2eproto::InitDefaultsAuthResultRequestImpl();
};
// -------------------------------------------------------------------

class DeleteServiceRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:crucis.DeleteServiceRequest) */ {
 public:
  DeleteServiceRequest();
  virtual ~DeleteServiceRequest();

  DeleteServiceRequest(const DeleteServiceRequest& from);

  inline DeleteServiceRequest& operator=(const DeleteServiceRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DeleteServiceRequest(DeleteServiceRequest&& from) noexcept
    : DeleteServiceRequest() {
    *this = ::std::move(from);
  }

  inline DeleteServiceRequest& operator=(DeleteServiceRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DeleteServiceRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DeleteServiceRequest* internal_default_instance() {
    return reinterpret_cast<const DeleteServiceRequest*>(
               &_DeleteServiceRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(DeleteServiceRequest* other);
  friend void swap(DeleteServiceRequest& a, DeleteServiceRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DeleteServiceRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  DeleteServiceRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DeleteServiceRequest& from);
  void MergeFrom(const DeleteServiceRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DeleteServiceRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 object_id = 1;
  void clear_object_id();
  static const int kObjectIdFieldNumber = 1;
  ::google::protobuf::uint64 object_id() const;
  void set_object_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:crucis.DeleteServiceRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 object_id_;
  mutable int _cached_size_;
  friend struct ::protobuf_service_5ffactory_5fparam_5fdefine_2eproto::TableStruct;
  friend void ::protobuf_service_5ffactory_5fparam_5fdefine_2eproto::InitDefaultsDeleteServiceRequestImpl();
};
// -------------------------------------------------------------------

class ReloadServiceRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:crucis.ReloadServiceRequest) */ {
 public:
  ReloadServiceRequest();
  virtual ~ReloadServiceRequest();

  ReloadServiceRequest(const ReloadServiceRequest& from);

  inline ReloadServiceRequest& operator=(const ReloadServiceRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReloadServiceRequest(ReloadServiceRequest&& from) noexcept
    : ReloadServiceRequest() {
    *this = ::std::move(from);
  }

  inline ReloadServiceRequest& operator=(ReloadServiceRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ReloadServiceRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReloadServiceRequest* internal_default_instance() {
    return reinterpret_cast<const ReloadServiceRequest*>(
               &_ReloadServiceRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(ReloadServiceRequest* other);
  friend void swap(ReloadServiceRequest& a, ReloadServiceRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReloadServiceRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  ReloadServiceRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ReloadServiceRequest& from);
  void MergeFrom(const ReloadServiceRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ReloadServiceRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 object_id = 2;
  void clear_object_id();
  static const int kObjectIdFieldNumber = 2;
  ::google::protobuf::uint64 object_id() const;
  void set_object_id(::google::protobuf::uint64 value);

  // uint32 service_type = 1;
  void clear_service_type();
  static const int kServiceTypeFieldNumber = 1;
  ::google::protobuf::uint32 service_type() const;
  void set_service_type(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:crucis.ReloadServiceRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 object_id_;
  ::google::protobuf::uint32 service_type_;
  mutable int _cached_size_;
  friend struct ::protobuf_service_5ffactory_5fparam_5fdefine_2eproto::TableStruct;
  friend void ::protobuf_service_5ffactory_5fparam_5fdefine_2eproto::InitDefaultsReloadServiceRequestImpl();
};
// -------------------------------------------------------------------

class SyncServicesResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:crucis.SyncServicesResponse) */ {
 public:
  SyncServicesResponse();
  virtual ~SyncServicesResponse();

  SyncServicesResponse(const SyncServicesResponse& from);

  inline SyncServicesResponse& operator=(const SyncServicesResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SyncServicesResponse(SyncServicesResponse&& from) noexcept
    : SyncServicesResponse() {
    *this = ::std::move(from);
  }

  inline SyncServicesResponse& operator=(SyncServicesResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SyncServicesResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SyncServicesResponse* internal_default_instance() {
    return reinterpret_cast<const SyncServicesResponse*>(
               &_SyncServicesResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  void Swap(SyncServicesResponse* other);
  friend void swap(SyncServicesResponse& a, SyncServicesResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SyncServicesResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  SyncServicesResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SyncServicesResponse& from);
  void MergeFrom(const SyncServicesResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SyncServicesResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool ret = 1;
  void clear_ret();
  static const int kRetFieldNumber = 1;
  bool ret() const;
  void set_ret(bool value);

  // @@protoc_insertion_point(class_scope:crucis.SyncServicesResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool ret_;
  mutable int _cached_size_;
  friend struct ::protobuf_service_5ffactory_5fparam_5fdefine_2eproto::TableStruct;
  friend void ::protobuf_service_5ffactory_5fparam_5fdefine_2eproto::InitDefaultsSyncServicesResponseImpl();
};
// -------------------------------------------------------------------

class BindServiceResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:crucis.BindServiceResponse) */ {
 public:
  BindServiceResponse();
  virtual ~BindServiceResponse();

  BindServiceResponse(const BindServiceResponse& from);

  inline BindServiceResponse& operator=(const BindServiceResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BindServiceResponse(BindServiceResponse&& from) noexcept
    : BindServiceResponse() {
    *this = ::std::move(from);
  }

  inline BindServiceResponse& operator=(BindServiceResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BindServiceResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BindServiceResponse* internal_default_instance() {
    return reinterpret_cast<const BindServiceResponse*>(
               &_BindServiceResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    8;

  void Swap(BindServiceResponse* other);
  friend void swap(BindServiceResponse& a, BindServiceResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BindServiceResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  BindServiceResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const BindServiceResponse& from);
  void MergeFrom(const BindServiceResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(BindServiceResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool ret = 1;
  void clear_ret();
  static const int kRetFieldNumber = 1;
  bool ret() const;
  void set_ret(bool value);

  // @@protoc_insertion_point(class_scope:crucis.BindServiceResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool ret_;
  mutable int _cached_size_;
  friend struct ::protobuf_service_5ffactory_5fparam_5fdefine_2eproto::TableStruct;
  friend void ::protobuf_service_5ffactory_5fparam_5fdefine_2eproto::InitDefaultsBindServiceResponseImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// NewServiceSingletonRequest

// uint32 service_type = 1;
inline void NewServiceSingletonRequest::clear_service_type() {
  service_type_ = 0u;
}
inline ::google::protobuf::uint32 NewServiceSingletonRequest::service_type() const {
  // @@protoc_insertion_point(field_get:crucis.NewServiceSingletonRequest.service_type)
  return service_type_;
}
inline void NewServiceSingletonRequest::set_service_type(::google::protobuf::uint32 value) {
  
  service_type_ = value;
  // @@protoc_insertion_point(field_set:crucis.NewServiceSingletonRequest.service_type)
}

// -------------------------------------------------------------------

// NewServiceRequest

// uint32 service_type = 1;
inline void NewServiceRequest::clear_service_type() {
  service_type_ = 0u;
}
inline ::google::protobuf::uint32 NewServiceRequest::service_type() const {
  // @@protoc_insertion_point(field_get:crucis.NewServiceRequest.service_type)
  return service_type_;
}
inline void NewServiceRequest::set_service_type(::google::protobuf::uint32 value) {
  
  service_type_ = value;
  // @@protoc_insertion_point(field_set:crucis.NewServiceRequest.service_type)
}

// uint64 object_id = 2;
inline void NewServiceRequest::clear_object_id() {
  object_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 NewServiceRequest::object_id() const {
  // @@protoc_insertion_point(field_get:crucis.NewServiceRequest.object_id)
  return object_id_;
}
inline void NewServiceRequest::set_object_id(::google::protobuf::uint64 value) {
  
  object_id_ = value;
  // @@protoc_insertion_point(field_set:crucis.NewServiceRequest.object_id)
}

// -------------------------------------------------------------------

// SyncServicesRequest

// repeated uint32 service_types = 1;
inline int SyncServicesRequest::service_types_size() const {
  return service_types_.size();
}
inline void SyncServicesRequest::clear_service_types() {
  service_types_.Clear();
}
inline ::google::protobuf::uint32 SyncServicesRequest::service_types(int index) const {
  // @@protoc_insertion_point(field_get:crucis.SyncServicesRequest.service_types)
  return service_types_.Get(index);
}
inline void SyncServicesRequest::set_service_types(int index, ::google::protobuf::uint32 value) {
  service_types_.Set(index, value);
  // @@protoc_insertion_point(field_set:crucis.SyncServicesRequest.service_types)
}
inline void SyncServicesRequest::add_service_types(::google::protobuf::uint32 value) {
  service_types_.Add(value);
  // @@protoc_insertion_point(field_add:crucis.SyncServicesRequest.service_types)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
SyncServicesRequest::service_types() const {
  // @@protoc_insertion_point(field_list:crucis.SyncServicesRequest.service_types)
  return service_types_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
SyncServicesRequest::mutable_service_types() {
  // @@protoc_insertion_point(field_mutable_list:crucis.SyncServicesRequest.service_types)
  return &service_types_;
}

// repeated uint32 service_ids = 2;
inline int SyncServicesRequest::service_ids_size() const {
  return service_ids_.size();
}
inline void SyncServicesRequest::clear_service_ids() {
  service_ids_.Clear();
}
inline ::google::protobuf::uint32 SyncServicesRequest::service_ids(int index) const {
  // @@protoc_insertion_point(field_get:crucis.SyncServicesRequest.service_ids)
  return service_ids_.Get(index);
}
inline void SyncServicesRequest::set_service_ids(int index, ::google::protobuf::uint32 value) {
  service_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:crucis.SyncServicesRequest.service_ids)
}
inline void SyncServicesRequest::add_service_ids(::google::protobuf::uint32 value) {
  service_ids_.Add(value);
  // @@protoc_insertion_point(field_add:crucis.SyncServicesRequest.service_ids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
SyncServicesRequest::service_ids() const {
  // @@protoc_insertion_point(field_list:crucis.SyncServicesRequest.service_ids)
  return service_ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
SyncServicesRequest::mutable_service_ids() {
  // @@protoc_insertion_point(field_mutable_list:crucis.SyncServicesRequest.service_ids)
  return &service_ids_;
}

// -------------------------------------------------------------------

// BindServiceRequest

// int32 service_type = 1;
inline void BindServiceRequest::clear_service_type() {
  service_type_ = 0;
}
inline ::google::protobuf::int32 BindServiceRequest::service_type() const {
  // @@protoc_insertion_point(field_get:crucis.BindServiceRequest.service_type)
  return service_type_;
}
inline void BindServiceRequest::set_service_type(::google::protobuf::int32 value) {
  
  service_type_ = value;
  // @@protoc_insertion_point(field_set:crucis.BindServiceRequest.service_type)
}

// -------------------------------------------------------------------

// AuthResultRequest

// .crucis.AuthErrorCode result = 1;
inline void AuthResultRequest::clear_result() {
  result_ = 0;
}
inline ::crucis::AuthErrorCode AuthResultRequest::result() const {
  // @@protoc_insertion_point(field_get:crucis.AuthResultRequest.result)
  return static_cast< ::crucis::AuthErrorCode >(result_);
}
inline void AuthResultRequest::set_result(::crucis::AuthErrorCode value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:crucis.AuthResultRequest.result)
}

// -------------------------------------------------------------------

// DeleteServiceRequest

// uint64 object_id = 1;
inline void DeleteServiceRequest::clear_object_id() {
  object_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 DeleteServiceRequest::object_id() const {
  // @@protoc_insertion_point(field_get:crucis.DeleteServiceRequest.object_id)
  return object_id_;
}
inline void DeleteServiceRequest::set_object_id(::google::protobuf::uint64 value) {
  
  object_id_ = value;
  // @@protoc_insertion_point(field_set:crucis.DeleteServiceRequest.object_id)
}

// -------------------------------------------------------------------

// ReloadServiceRequest

// uint32 service_type = 1;
inline void ReloadServiceRequest::clear_service_type() {
  service_type_ = 0u;
}
inline ::google::protobuf::uint32 ReloadServiceRequest::service_type() const {
  // @@protoc_insertion_point(field_get:crucis.ReloadServiceRequest.service_type)
  return service_type_;
}
inline void ReloadServiceRequest::set_service_type(::google::protobuf::uint32 value) {
  
  service_type_ = value;
  // @@protoc_insertion_point(field_set:crucis.ReloadServiceRequest.service_type)
}

// uint64 object_id = 2;
inline void ReloadServiceRequest::clear_object_id() {
  object_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ReloadServiceRequest::object_id() const {
  // @@protoc_insertion_point(field_get:crucis.ReloadServiceRequest.object_id)
  return object_id_;
}
inline void ReloadServiceRequest::set_object_id(::google::protobuf::uint64 value) {
  
  object_id_ = value;
  // @@protoc_insertion_point(field_set:crucis.ReloadServiceRequest.object_id)
}

// -------------------------------------------------------------------

// SyncServicesResponse

// bool ret = 1;
inline void SyncServicesResponse::clear_ret() {
  ret_ = false;
}
inline bool SyncServicesResponse::ret() const {
  // @@protoc_insertion_point(field_get:crucis.SyncServicesResponse.ret)
  return ret_;
}
inline void SyncServicesResponse::set_ret(bool value) {
  
  ret_ = value;
  // @@protoc_insertion_point(field_set:crucis.SyncServicesResponse.ret)
}

// -------------------------------------------------------------------

// BindServiceResponse

// bool ret = 1;
inline void BindServiceResponse::clear_ret() {
  ret_ = false;
}
inline bool BindServiceResponse::ret() const {
  // @@protoc_insertion_point(field_get:crucis.BindServiceResponse.ret)
  return ret_;
}
inline void BindServiceResponse::set_ret(bool value) {
  
  ret_ = value;
  // @@protoc_insertion_point(field_set:crucis.BindServiceResponse.ret)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace crucis

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_service_5ffactory_5fparam_5fdefine_2eproto__INCLUDED
